---
permalink: deploy/recovery-deployment.html 
sidebar: sidebar 
keywords:  
summary: 如果您遺失用於 VMware vSphere 設定的 ONTAP 工具、但 ONTAP 仍在運作、則可以使用 ONTAP 來恢復用於 VMware vSphere 設定的 ONTAP 工具。當您遺失設定時、請將設定正常關閉。 
---
= 針對 VMware vSphere 設定復原您的 ONTAP 工具
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您遺失用於 VMware vSphere 設定的 ONTAP 工具、您可以使用 ONTAP Volume 資料中的可用資料、來復原用於 VMware vSphere 設定的 ONTAP 工具。當您遺失設定時、請將設定正常關閉。


NOTE: 如果 vCenter Server 或 ONTAP 資料管理軟體發生問題、您將無法恢復用於 VMware vSphere 設定的 ONTAP 工具。

*步驟*

. 登入 vSphere 伺服器。
. 瀏覽至您要部署 OVA 的資源集區、節點叢集或主機。
. 以滑鼠右鍵按一下所需的位置、然後選取 * 部署 OVF 範本 * 。
. 您可以輸入 _.ova_ 檔案的 URL 、或瀏覽至儲存 _.ova_ 檔案的資料夾、然後選取 * 下一步 * 。
+

NOTE: 您應該使用與安裝恢復設定相同的 OVA 建置。

. 選取虛擬機器的名稱和資料夾、然後選取 * 下一步 * 。
. 選取主機並選取 * 下一步 * 。
. 檢閱範本摘要、然後選取 * 下一步 * 。
. 閱讀並接受授權合約、然後選擇 * 下一步 * 。
. 在 * 組態 * 視窗中、選取 * 恢復 * 選項。
. 在 * 選取儲存設備 * 視窗中、選取組態和磁碟檔案的儲存設備。
. 在 * 選取網路 * 視窗中、為每個來源網路選取目的地網路。
+

NOTE: 您需要保留負載平衡器 IP 位址和 Kubernetes API Server IP 位址。您可以變更節點 IP 位址、也可以保留相同的 IP 位址。

. 選擇 * 自訂範本 * > * 系統組態 * 視窗。輸入下列詳細資料：
+
.. 應用程式使用者名稱和密碼：此使用者名稱和密碼用於在 vCenter Server 中登錄 VASA 提供者和 SRA 。這可能與初始部署期間提供的使用者名稱和密碼不同。
.. 預設會選取 * 啟用 ASUP* 核取方塊。




AutoSupport 只能在部署期間啟用或停用。...在 *ASUP Proxy URL* 欄位中、提供此 URL 以避免 AutoSupport 資料傳輸的防火牆封鎖。...系統管理員使用者名稱和系統管理員密碼：這是用來登入 ONTAP 工具管理員的密碼。這可能與初始部署期間提供的使用者名稱和密碼不同。...在 *NTP Servers* 欄位中輸入您的 NTP 伺服器資訊。...維護使用者密碼：用於授予維護主控台選項的存取權。。在 * 自訂範本 * > * 部署組態 * 視窗中、輸入部署期間提供的詳細資料。本節中的所有值應與初始部署期間提供的值相同、資料 LIF 值除外。


NOTE: 儲存 SVM 名稱不應像儲存還原資料的位置一樣變更。這也適用於直接新增的 SVM 使用者帳戶。。對於 HA 部署恢復，請提供以下詳細信息： ...內容庫詳細資料。vCenter 組態詳細資料。。在「 * 自訂範本 * > * 節點組態 * 」視窗中、輸入您嘗試恢復、非 HA 或 HA 設定的詳細資料。。查看 * 準備完成 * 視窗中的詳細資料、選取 * 完成 * 。

+ 在建立部署工作時、進度會顯示在 vSphere 工作列中。。在工作完成後開啟虛擬機器電源。

+ 開始安裝。您可以在 VM 的 Web 主控台中追蹤安裝進度。在安裝過程中、會驗證節點組態。在 OVF 表單的自訂範本下的不同區段下提供的輸入都會經過驗證。若有任何差異、對話方塊會提示您採取修正行動。。在對話方塊提示中進行必要的變更。使用 Tab 鍵瀏覽面板以輸入您的值 * 確定 * 或 * 取消 * 。。選擇 *OK* 或 * 取消 * 時、將再次驗證提供的值。ONTAP Tools for VMware 可讓您嘗試三次修正任何無效值。如果三次嘗試後仍無法修正問題、產品安裝將會停止、建議您嘗試在新的 VM 上安裝。。安裝成功之後、 Web 主控台會顯示 VMware vSphere 的 ONTAP 工具狀態。安裝成功之後、您應該依照頁面中的準則、手動編輯硬體需求 link:../deploy/sizing-requirements.html["部署 VMware vSphere ONTAP 工具的必要條件"] 。
