---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: 您應該先設定儲存系統、再執行 Site Recovery Manager （ SRM ）的儲存複寫介面卡（ SRA ）。 
---
= 為 SAN 和 NAS 環境設定 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該先設定儲存系統、再執行 Site Recovery Manager （ SRM ）的儲存複寫介面卡（ SRA ）。



== 為 SAN 環境設定 SRA

*您需要的是什麼*

您應該在受保護的站台和還原站台上安裝下列程式：

* SRM
+
有關安裝SRM的說明文件、請參閱VMware網站。

+
https://docs.vmware.com/en/Site-Recovery-Manager/index.html["VMware Site Recovery Manager文件"]

* SRA
+
介面卡已安裝在 SRM 上。



*步驟*

. 確認主ESXi主機已連線至受保護站台上主要儲存系統的LUN。
. 驗證 LUN 是否位於 igroup 中 `ostype`、且主儲存系統上的選項設為 _VMware_ 。
. 確認恢復站台上的 ESXi 主機與儲存虛擬機器（ SVM ）有適當的 iSCSI 連線。次要站台 ESXi 主機應可存取次要站台儲存設備、且主要站台 ESXi 主機應可存取主要站台儲存設備。
+
您可以透過驗證 ESXi 主機是否已在 SVM 上連接本機 LUN 、或是 `iscsi show initiators` SVM 上的命令來執行此動作。檢查 ESXi 主機中對應 LUN 的 LUN 存取權、以驗證 iSCSI 連線能力。





== 為 NAS 環境設定 SRA

*您需要的是什麼*

您應該在受保護的站台和還原站台上安裝下列程式：

* SRM
+
如需安裝SRM的相關文件、請參閱VMware網站。

+
https://docs.vmware.com/en/Site-Recovery-Manager/index.html["VMware Site Recovery Manager文件"]

* SRA
+
介面卡安裝在SRM和SRA伺服器上。



*步驟*

. 確認受保護站台的資料存放區包含已向vCenter Server註冊的虛擬機器。
. 確認受保護站台的ESXi主機已從儲存虛擬機器（SVM）掛載NFS匯出磁碟區。
. 使用Array Manager精靈將陣列新增至SRM時、請確認「* NFS Addresses *（* NFS位址*）」欄位中已指定有效位址、例如有NFS匯出的IP位址、主機名稱或FQDN。
.  `ping`在恢復站台的每個 ESXi 主機上使用命令、驗證主機是否有 VMkernel 連接埠、可存取用於從 SVM 匯出 NFS 的 IP 位址。

