---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords:  
summary: 下節說明文件中所使用的主要概念和詞彙。 
---
= 關鍵概念與詞彙
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
下節說明文件中所使用的主要概念和詞彙。



=== 憑證授權單位（ CA ）

CA 是發行安全通訊端層（ SSL ）憑證的信任實體。



=== 雙堆疊

雙堆疊網路是支援同時使用 IPv4 和 IPv6 位址的網路環境。



=== 高可用度（HA）

叢集節點是以 HA 配對方式設定、以進行不中斷營運。



=== 邏輯單元編號（LUN）

LUN 是用於識別儲存區域網路（ SAN ）內邏輯單元的編號。這些可定址的裝置通常是透過小型電腦系統介面（ SCSI ）傳輸協定或其封裝衍生工具之一存取的邏輯磁碟。



=== ONTAP 工具管理器

ONTAP 工具管理員可透過託管的 vCenter Server 執行個體和已建立的儲存後端、為 VMware vSphere 管理員提供更多的 ONTAP 工具控制權。ONTAP tools Manger 可協助管理 vCenter Server 執行個體、儲存設備後端、憑證、密碼和記錄套件下載。



=== 開放式虛擬應用裝置（ OVA ）

ova 是一套開放式標準、用於封裝及散佈必須在虛擬機器上執行的虛擬應用裝置或軟體。



=== SnapMirror Active （ SMAS ）

SnapMirror 主動式同步可讓業務服務持續運作、即使整個站台故障也沒問題、支援應用程式使用次要複本以透明方式容錯移轉。需要手動介入或自訂指令碼、才能使用 SnapMirror 主動同步觸發容錯移轉。



=== 儲存複寫介面卡（SRA）

SRA 是安裝在 SRM 應用裝置內的儲存廠商專屬軟體。此介面卡可在 Site Recovery Manager 與儲存虛擬機器（ SVM ）層級的儲存控制器之間、以及叢集層級組態之間進行通訊。



=== 儲存虛擬機器（ SVM ）

與在 Hypervisor 上執行的虛擬機器一樣、 SVM 是一個邏輯實體、可將實體資源抽象化。SVM 包含資料磁碟區和一或多個生命體、可透過這些生命體將資料提供給用戶端。



=== 虛擬機器檔案系統（ VMFS ）

VMFS 是專為在 VMware vSphere 環境中儲存虛擬機器檔案而設計的叢集式檔案系統。



=== 虛擬磁碟區（vVols）

VVols 為虛擬機器所使用的儲存設備提供磁碟區層級抽象化。它包含多項優點、可替代傳統 LUN 的使用方式。vVol 資料存放區通常與單一 LUN 相關聯、該 LUN 可作為 vVols 的容器。



=== VM 儲存原則

VM 儲存原則是在 vCenter Server 的原則和設定檔下建立。對於 vVols 、請使用 NetApp vVols 儲存類型提供者的規則來建立規則集。



=== VMware Site Recovery Manager （ SRM ）

SRM 可為 VMware 虛擬環境提供營運不中斷、災難恢復、站台移轉及不中斷營運的測試功能。



=== VMware vSphere API for Storage A感知 （ VASA ）

Vasa 是一組 API 、可將儲存陣列與 vCenter Server 整合以進行管理。此架構以多個元件為基礎、包括處理 VMware vSphere 與儲存系統之間通訊的 VASA Provider 。



=== VMware vSphere 儲存 API - 陣列整合（ VAAI ）

VAAI 是一組 API 、可在 VMware vSphere ESXi 主機和儲存裝置之間進行通訊。這些 API 包括一組主機用來將儲存作業卸載到陣列的原始作業。VAAI 可大幅改善儲存密集工作的效能。



=== vVols資料存放區

VVols 資料存放區是 VVols 容器的邏輯資料存放區呈現、由 VASA Provider 建立及維護。



=== 零RPO

RPO 是指恢復點目標、這是在指定時間內可接受的資料遺失量。零 RPO 表示無法接受資料遺失。
