---
permalink: configure/create-vvols-datastore.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用新的磁碟區或現有的磁碟區來建立 vVols 資料存放區。您也可以結合現有磁碟區和新磁碟區來建立 vVols 資料存放區。 
---
= 建立資料存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您在主機叢集層級建立資料存放區時、會在目的地的所有主機上建立並掛載資料存放區、而且只有在目前使用者有權執行的情況下、才會啟用該動作。

「建立資料存放區」動作精靈支援建立 NFS 、 VMFS 和 VVols 資料存放區。



== 建立 VVols 資料存放區

您可以使用新的磁碟區或現有的磁碟區來建立 vVols 資料存放區。您無法以現有和新磁碟區的混合形式建立 vVols 資料存放區。


NOTE: 檢查以確保根集合體未對應至 SVM 。

.開始之前
請確定 VASA 提供者已向所選的 vCenter 登錄。

.步驟
. 使用登入 vSphere 用戶端 `\https://vcenterip/ui`
. 以滑鼠右鍵按一下主機系統、主機叢集或資料中心、然後選取 * NetApp ONTAP tools* > * Create Datastore* 。
. 在 * 類型 * 窗格中、選取 * 資料存放區類型 * 中的 vVols 。
. 在 * 名稱與傳輸協定 * 窗格中、提供 * 資料存放區名稱 * 和 * 傳輸協定 * 資訊。
. 在 *Storage* 窗格中，選擇 *Platform* 和 *storage VM* 。在 * 進階選項 * 區段中、視情況選取自訂匯出原則（適用於 NFS 傳輸協定）或自訂啟動器群組名稱（適用於 iSCSI 傳輸協定）。
+
** 平台和非對稱選項可協助您篩選出 SVM 下拉式選項。您應該選取 SVM 來建立或使用磁碟區來建立資料存放區。
** 只有在上一個步驟中選取了 iSCSI 、且在平台下拉式選單中選取了效能或容量時、才會顯示 * 非對稱 * 切換按鈕。
** 選取 AFF 平台的 * 非對稱 * 切換按鈕、並停用 ASA 平台的 * 非對稱 * 切換按鈕。


. 在 * 儲存屬性 * 窗格中、您可以建立新的磁碟區或使用現有的磁碟區。建立新磁碟區時、您可以在資料存放區上啟用 QoS 。
. 在 * 摘要 * 窗格中檢閱您的選擇、然後按一下 * 完成 * 。VVols Datastore 會建立並掛載於所有主機上。




== 建立 NFS 資料存放區

VMware 網路檔案系統（ NFS ）資料存放區使用 NFS 傳輸協定、透過網路將 ESXi 主機連線至共用儲存裝置。NFS 資料存放區通常用於 VMware vSphere 環境、並提供多項優點、例如簡易性和靈活度。

.步驟
. 使用登入 vSphere 用戶端 `\https://vcenterip/ui`
. 以滑鼠右鍵按一下主機系統、主機叢集或資料中心、然後選取 * NetApp ONTAP tools* > * Create Datastore* 。
. 在 * 類型 * 窗格中、在 * 資料存放區類型 * 中選取 NFS 。
. 在 * 名稱和傳輸協定 * 窗格中、輸入資料存放區名稱、大小和傳輸協定資訊。在進階選項中、選取 * 資料存放區叢集 * 和 * Kerberos 驗證 * 。
+

NOTE: Kerberos 驗證只有在選取 NFS 4.1 傳輸協定時才能使用。

. 在 * Storage* 窗格中、選取 * 平台 * 和 * 儲存 VM* 。您可以在 * 進階選項 * 區段中選取 * 自訂匯出原則 * 。
+
** * 非對稱 * 切換按鈕只有在平台下拉式選單中選取效能或容量時才會顯示。
** * 平台下拉式清單中的任何 * 選項可讓您查看 vCenter 的所有 SVM 、無論平台或非對稱式旗標為何。


. 在 * 儲存屬性 * 窗格中、選取要建立磁碟區的集合體。在進階選項中、視需要選擇 * 空間保留 * 和 * 啟用 QoS* 。
. 檢閱「 * 摘要 * 」窗格中的選項、然後按一下「 * 完成 * 」。


NFS 資料存放區會建立並掛載於所有主機上。



== 建立 VMFS 資料存放區

虛擬機器檔案系統（ VMFS ）是專為在 VMware vSphere 環境中儲存虛擬機器檔案而設計的叢集式檔案系統。它可讓多個 ESXi 主機同時存取相同的虛擬機器檔案、提供 VMotion 和高可用度等功能。

.步驟
. 使用登入 vSphere 用戶端 `\https://vcenterip/ui`
. 在主機系統或主機叢集或資料存放區上按一下滑鼠右鍵、然後選取 * NetApp ONTAP tools* > * Create Datastore* 。
. 在 * 類型 * 窗格中、在 * 資料存放區類型 * 中選取 VMFS 。
. 在 * 名稱和傳輸協定 * 窗格中、輸入資料存放區名稱、大小和傳輸協定資訊。在窗格的 * 進階選項 * 區段中、選取您要新增此資料存放區的資料存放區叢集。
. 在 Storage （儲存）窗格中選取 Platform and storage VM （平台和儲存 VM ）。選取非對稱切換按鈕。在窗格的 * 進階選項 * 區段中提供 * 自訂啟動器群組名稱 * （選用）。您可以為資料存放區選擇現有的 igroup 、也可以使用自訂名稱建立新的 igroup 。
+
如果您在平台下拉式清單中選擇 * 任何 * 選項、則無論平台或非對稱式旗標為何、您都可以看到屬於 vCenter 一部分的所有 SVM 。

. 從儲存屬性窗格中、從下拉式功能表中選取 * Aggregate * 。根據需要從 *Advanced options* 部分中選擇 *Space ReservoS* 、 * Use existing volume * 和 * Enable QoS* 選項，並根據需要提供詳細信息。
. 檢閱 * 摘要 * 窗格中的資料存放區詳細資料、然後按一下 * 完成 * 。VMFS 資料存放區會建立並掛載於所有主機上。

